{{ if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: lobe-chat
  labels:
    {{- include "lobe-chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.secret.OPENAI_API_KEY | b64enc }}
  ACCESS_CODE: {{ .Values.secret.ACCESS_CODE | b64enc }}
{{- end}}