apiVersion: v1
kind: Service
metadata:
  name: {{ include "lobe-chat.fullname" . }}
  labels:
    {{- include "lobe-chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: networking
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lobe-chat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: workload
